### ISSUE TITLE
json: cannot unmarshal object into Go value of type []github.User

### ISSUE THREAD

**Issue by ntindall** [kirillrogovoy/pullkee#3]
*go version go1.10.1 darwin/amd64*

I followed the instructions in the README, but am getting this on every repo I try:

```sh
$ GITHUB_CREDS="ntindall:my_token" pullkee --limit 50 kirillrogovoy/pullkee
Github rate limit details:
Limit: 5000
Remaining: 4433
Reset: 2018-04-26 23:59:49 -0700 PDT

Getting Pull Request list...
Attaching details...
[                                                  ]An unexpected error occurred:

json: cannot unmarshal object into Go value of type []github.User
```

I didn't get the chance to look into this, but thought I would flag @kirillrogovoy

**Comment by kirillrogovoy** [comment]
Hey Nathan,

Thanks for reporting this!

I'm going to look into this in the following days and will let you know.

**Comment by kirillrogovoy** [comment]
Ok, I figured out what was wrong.

Apparently, the API for https://developer.github.com/v3/pulls/review_requests/ has changed since the last time I checked.

As you might notice in [this Web archive as of Nov 23, 2017](https://web.archive.org/web/20171123172617/https://developer.github.com/v3/pulls/review_requests/), the response schema used to be not aware of the Teams functionality thus being just an array of users. And now it's an object with `users` and `teams` arrays.

Please, give it another try with [the latest release](https://github.com/kirillrogovoy/pullkee/releases).

Thanks again for reporting this!
